[package]
name = "gpui_examples"
publish = false
edition.workspace = true

[dependencies]
gpui_flowkit.workspace = true

gpui.workspace = true
glam.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
core-text.workspace = true

[[example]]
name = "gpui_canvas"
path = "src/canvas.rs"
